# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build tools

on:
  schedule:
    - cron: "0 0 * * 0" # once a week every Sunday at midnight
  workflow_dispatch:
    
env:
  # We use a debug build for slightly faster build times
  BUILD_CONFIGURATION: Debug
  BUILD_PLATFORM: Win32

# These should really be moved into the one solution.
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Fetch required submodules only
      run: |
        git submodule update --init deps/dx9sdk

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build tools
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration="${{env.BUILD_CONFIGURATION}}" /p:Platform="${{env.BUILD_PLATFORM}}" Tools.sln
